### PR TITLE
Development Workflow

### PR DESCRIPTION
**Pull request by pwltr**
This PR should serve as an aggregate for all commits on `feat/workflow` branches over all citadel repos for this change.
For easy testing use `citadel-dev init -b feat/workflow`.

### citadel-dev
- add possiblity to specify branch for `citadel-dev init` command (temporary)
- add possiblity to clone via `ssh`
- update `docker-compose.override.yml` to reflect changes in Dockerfiles, improvements for dev

### core
- add network settings for new UI (development)
- set `DEVICE_HOSTNAME` env var, needed for dashboard HMR config in vite 

### dashboard
- add Dockerfile development stage
- run container process as user "node"
- update HMR config in `vite.config.js` to use polling for development in docker

### ui
- add Dockerfile development stage
- run container process as user "node"
- update HMR config in `next.config.js` to use polling for development in docker 

### middleware
- add Dockerfile development stage
- switch to node:alpine for smaller image size
- run container process as user "node"
- add automatic reloading in development w/ `nodemon` & `tsc --watch`

### manager
- add Dockerfile development stage
- switch to node:alpine for smaller image size
- run container process as user "node"
- ~add automatic reloading in development w/ `nodemon` & `tsc --watch`~

## Image Size (production)

|  image     |         before                       |            after                           |
|------------------|-----------------------------------|---------------------------------------|
| dashboard    |   198MB       |     122MB          |
| middleware  |   209MB  |     142MB                        |
| manager      |   260MB          |     186MB           |

## Image Build Duration (production)

|  image     |         before                       |            after                           |
|------------------|-----------------------------------|---------------------------------------|
| dashboard    |                                          |                                              |
| middleware  |                                           |                                             |
| manager      |                                           |                                              |

## Todo
- [x] add HMR
  - [x] dashboard
  - [ ] manager (disabled because of issues with JWT on server restart)
  - [x] middleware
  - [x] ui
- [ ] optimize image size & build speed
- [x] ~~make development with `runcitadel/sdk` easier with `yarn link`~~
- [x] update readme

### CODE REVIEW

**Comment by pwltr** [comment]
@AaronDewes @WilliamConnatser 
This should be very usable now. Had to disable file watching/auto restarting for the manager though, as there are some issues on server restart with JWT. This will probably have to be fixed in the manager code itself. Until then please rebuild the container after you made changes. `docker compose up --build -d manager`

Also please note that after vagrant has finished booting, yarn will now start installing dependencies for all 4 repos. This takes about 10 minutes on my machine. Have to do that on container runtime so we have node_modules on the host as well for editor intellisense & plugins to work. Check progress with `docker logs -f dashboard` (dashboard takes the longest).

EDIT: actually you have to rebuild both the manager and the middleware after changes to manager
```
docker rm -f manager middleware
docker compose up --build -d middleware
```
This will rebuild manager also because middleware depends on it. Still trying to understand what's happening here.

**Review by AaronDewes — APPROVED** [review]
I haven't tested this yet, but it seems good

**Comment by pwltr** [comment]
@AaronDewes 
Should I rebase [core/feat/workflow](https://github.com/runcitadel/core/tree/feat/workflow) onto the main branch or stable? I would merge this now.

**Comment by AaronDewes** [comment]
Please rebase it on beta. Main is deprecated and shouldn't be changed anymore

**Pull request merged**
